services:
  # Next.jsアプリケーション
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SKIP_AUTH: true
      USE_LOCAL_AGENT: true
      LOCAL_AGENT_URL: http://sake-agent:8080
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      - dynamodb-local
    networks:
      - app-network

  # 日本酒推薦エージェント（本番用）
  sake-agent:
    build:
      context: ./agentcore
      dockerfile: Dockerfile
      target: production
    image: sake-agent:latest
    container_name: sake-recommendation-agent
    environment:
      - AWS_REGION=${AWS_REGION:-ap-northeast-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AGENTCORE_RUNTIME_ID=${AGENTCORE_RUNTIME_ID}
      - AGENTCORE_MEMORY_ID=${AGENTCORE_MEMORY_ID}
      - AGENTCORE_GATEWAY_URL=${AGENTCORE_GATEWAY_URL}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-anthropic.claude-3-sonnet-20240229-v1:0}
      - BEDROCK_REGION=${BEDROCK_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - MAX_RECOMMENDATIONS=${MAX_RECOMMENDATIONS:-5}
      - RECOMMENDATION_TIMEOUT=${RECOMMENDATION_TIMEOUT:-10}
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb-data:/home/dynamodblocal
    networks:
      - app-network

  # DynamoDB Admin (Webベースの管理ツール)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - app-network

volumes:
  dynamodb-data:
    driver: local

networks:
  app-network:
    driver: bridge