import type { Metadata } from "next";
import { Zen_Kurenaido, Yuji_Syuku } from "next/font/google";
import "./globals.css";

const zenKurenaido = Zen_Kurenaido({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-zen-kurenaido",
});

const yujiSyuku = Yuji_Syuku({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-yuji-syuku",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${zenKurenaido.variable} ${yujiSyuku.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
